### ISSUE TITLE
unable to get it installed on kali linux

### ISSUE THREAD

**Issue by bigmo0x0** [nikitastupin/clairvoyance#113]
running the installation command 
pip install clairvoyance
clairvoyance https://rickandmortyapi.com/graphql -o schema.json
throws the following errors

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.      
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement clairvoyance (from versions: none)
ERROR: No matching distribution found for clairvoyance

**Comment by Privat33r-dev** [comment]
Hi!

Can you try with newer Python Version, please? What is your OS?

**Comment by bigmo0x0** [comment]
using the docker option gives the following error

docker run --rm nikitastupin/clairvoyance https://www.thefork.com/api/graphql
2024-09-23 13:10:27     INFO    | Starting blind introspection on https://www.thefork.com/api/graphql...
2024-09-23 13:10:27     INFO    | Iteration 1
2024-09-23 13:10:28     WARNING | Unable to get typename from query { IAmWrongField }.
                      Field Suggestion might not be enabled on this endpoint. Using default "Query
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/clairvoyance/__main__.py", line 4, in <module>
    cli()
  File "/clairvoyance/cli.py", line 142, in cli
    asyncio.run(
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/clairvoyance/cli.py", line 89, in blind_introspection
    schema = await oracle.clairvoyance(
  File "/clairvoyance/oracle.py", line 578, in clairvoyance
    valid_fields = await probe_valid_fields(
  File "/clairvoyance/oracle.py", line 209, in probe_valid_fields
    result = await task
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/clairvoyance/oracle.py", line 176, in __probation
    errors = response['errors']
KeyError: 'errors'
2024-09-23 13:10:29     ERROR   | Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7efc7ac173d0>

**Comment by Privat33r-dev** [comment]
> using the docker option gives the following error
> 
> docker run --rm nikitastupin/clairvoyance https://www.thefork.com/api/graphql 2024-09-23 13:10:27 INFO | Starting blind introspection on https://www.thefork.com/api/graphql... 2024-09-23 13:10:27 INFO | Iteration 1 2024-09-23 13:10:28 WARNING | Unable to get typename from query { IAmWrongField }. Field Suggestion might not be enabled on this endpoint. Using default "Query Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/clairvoyance/**main**.py", line 4, in cli() File "/clairvoyance/cli.py", line 142, in cli asyncio.run( File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete return future.result() File "/clairvoyance/cli.py", line 89, in blind_introspection schema = await oracle.clairvoyance( File "/clairvoyance/oracle.py", line 578, in clairvoyance valid_fields = await probe_valid_fields( File "/clairvoyance/oracle.py", line 209, in probe_valid_fields result = await task File "/usr/local/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one return f.result() # May raise f.exception(). File "/clairvoyance/oracle.py", line 176, in __probation errors = response['errors'] KeyError: 'errors' 2024-09-23 13:10:29 ERROR | Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x7efc7ac173d0>

Have you tried following our [troubleshooting guide](https://github.com/nikitastupin/clairvoyance/blob/6f7aaa4be48df30f18c640c3d718380325fc10f4/troubleshooting.md)?
