### ISSUE TITLE
server not connecting error

### ISSUE THREAD

**Issue by mojidoji** [nikitastupin/clairvoyance#115]
hi, the tool has some problems, can't resolve or connect to the servers and can't get the schema out of it

WARNING | Error posting to https://rickandmortyapi.com/graphql: Server disconnected
```Traceback (most recent call last):
  File "/usr/local/bin/clairvoyance", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/clairvoyance/cli.py", line 142, in cli
    asyncio.run(
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/clairvoyance/cli.py", line 89, in blind_introspection
    schema = await oracle.clairvoyance(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/clairvoyance/oracle.py", line 594, in clairvoyance
    field, args = await task
                  ^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 615, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/clairvoyance/oracle.py", line 535, in explore_field
    arg_names = await probe_args(
                ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/clairvoyance/oracle.py", line 272, in probe_args
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/clairvoyance/oracle.py", line 228, in probe_valid_args
    if 'errors' not in response:
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2024-10-21 05:53:51     ERROR   | Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa7dd2713d0>```

**Comment by Privat33r-dev** [comment]
[Rick and Morty API GraphQL](https://rickandmortyapi.com/graphql) bans IP after a while. I would suggest to use a slow mode (`-p slow`) and vpn/proxy (TOR would suffice).

**Comment by Privat33r-dev** [comment]
@mojidoji, has your issue been resolved?

**Comment by mojidoji** [comment]
> [Rick and Morty API GraphQL](https://rickandmortyapi.com/graphql) bans IP after a while. I would suggest to use a slow mode (`-p slow`) and vpn/proxy (TOR would suffice).

ah no, it seems like i can't resolve any result and it's not even connecting to extract the schema 

```WARNING | Error posting to https://ravro.ir/api/graphql ```

**Comment by Privat33r-dev** [comment]
@mojidoji have you tried our [troubleshooting guide](https://github.com/nikitastupin/clairvoyance/blob/main/troubleshooting.md)?

If it does not help, can you provide full command that you try and circumstances, for example, program started to run and stopped or it shows an error straightaway.
