### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'

### ISSUE THREAD

**Issue by thistehneisen** [nikitastupin/clairvoyance#29]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/xxx/Code/Python/clairvoyance/clairvoyance/__main__.py", line 96, in <module>
    schema = oracle.clairvoyance(
  File "/Users/xxx/Code/Python/clairvoyance/clairvoyance/oracle.py", line 435, in clairvoyance
    root_typenames = fetch_root_typenames(config)
  File "/Users/xxx/Code/Python/clairvoyance/clairvoyance/oracle.py", line 412, in fetch_root_typenames
    response = graphql.post(
  File "/Users/xxx/Code/Python/clairvoyance/clairvoyance/graphql.py", line 18, in post
    retries = urllib3.util.Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

Is this expected?

**Comment by nikitastupin** [comment]
Hi @thistehneisen,

It looks like you're using version of `urllib3` that doesn't support `allowed_methods` parameter. As far as I remember they've deprecated `allowed_methods` (it's called some other name now).
