### ISSUE TITLE
KeyError: 'errors'

### ISSUE THREAD

**Issue by BreakALegCml** [nikitastupin/clairvoyance#99]
linux 
command：docker run --rm nikitastupin/clairvoyance https://www.xxxx.au/graphql -o schema.json

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/clairvoyance/__main__.py", line 4, in <module>
    cli()
  File "/clairvoyance/cli.py", line 142, in cli
    asyncio.run(
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/clairvoyance/cli.py", line 89, in blind_introspection
    schema = await oracle.clairvoyance(
  File "/clairvoyance/oracle.py", line 578, in clairvoyance
    valid_fields = await probe_valid_fields(
  File "/clairvoyance/oracle.py", line 209, in probe_valid_fields
    result = await task
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/clairvoyance/oracle.py", line 176, in __probation
    errors = response['errors']
KeyError: 'errors'
2024-05-10 14:07:59 	ERROR	| Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f207b4cd150>

**Comment by shopnobuzz** [comment]
Same issues here!
